sprint-1/step-2
EvgeniyBudaev/react-burger pull request #2
Opened 2021-12-07 05:47 UTC by EvgeniyBudaev

1) Открытие модального окна по клику на карточку ингредиента в BurgerConstructor и BurgerIngredients;
2) Открытие модального окна по клику на кнопку "Оформить заказ";
3) Данные приходят с API.

2021-12-07 19:17 UTC, grishbar requested changes
Прекраснейшая работа, круто, что все сделал на ts прекрасно пользуешься useMemo прикольно, что воспользовался библиотекой для запросов и для модалки, есть пара мест, которые надо исправить, чтобы принять работу.
В ТЗ явно не сказано, но все ингредиенты должны быть на одной странице, и табы просто скроллят до них, не думаю, что твое решение критично, но будет лучше, если сделаешь как у всех. Так как на следующих этапах будет задание реализовать эти табы.
И добавь обработку статуса ответа при запросе на бэкенд.
А так отличная работа, продолжай в том же духе!

2021-12-07 19:17 UTC, grishbar commented on src/api/menu.ts
> +const baseUrl = "https://norma.nomoreparties.space/api/ingredients";
`можно лучше`
не совсем корректное название переменной это скорее у тебя INGREDIENTS_URL, и такие константы принято называть в SNAKE_CASE, так сразу понятно, что эту переменную не надо менять

2021-12-07 19:17 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
> +                    ingredients.map(product => (
`можно лучше`
немного странно, что у тебя массив ingredients, а в ним идешь по продуктам а не ингредиентам, кажется, должно быть вот так:
`ingredients.map(ingredient => (`

2021-12-07 19:17 UTC, grishbar commented on src/components/ingredient-details/ingredient-details.module.css
> +}
`можно лучше`
старайся избегать комбинаторов по возможности, очень тяжело в будущем поддерживать такой код, и он очень чреват неожиданными багами, лучше всегда сделать отдельный класс и задать стили под него

2021-12-07 19:17 UTC, grishbar commented on src/components/order/order.tsx
> +    const BUN = "bun";
`можно лучше`
такое лучше выносить из компонента, чтобы не пересоздавать постоянно переменную

2021-12-07 19:17 UTC, grishbar commented on src/components/order/order.tsx
> +    }, [ingredients]);
`отлично` отлично воспользовался useMemo и reduce

2021-12-07 19:17 UTC, grishbar commented on src/components/order/order.tsx
> +    }, [ingredients]);
`можно лучше`
правильней будет назвать mains так как с бэка тебе приходит тип main у ингридентов не булок, будет лучше если везде будут консистентые данные

2021-12-07 19:17 UTC, grishbar commented on src/components/order/order.tsx
> +                setIsLoading(false);
`надо исправить`
добавь обработку на response.ok, так как запрос может выполниться, но прийти с ошибкой, и он не попадет в catch блок

2021-12-08 08:33 UTC, EvgeniyBudaev commented on src/components/order/order.tsx
> +                setIsLoading(false);
В замечании указано обработать статус ответа.  Такое решение устраивает? В файле menu.ts, если все ок то возвращается reponse.data, если же нет то передает error. 
`
export const fetchBurgerIngredients = (): Promise<AxiosResponse> => {
    return axios
        .get<ISearchResponse>(INGREDIENTS_URL)
        .then(response => response.data)
        .catch(error => error);
};
`
В компоненте если мы получили error, то красиво это обрабатываем и показываем пользователю в виде всплывающего окна AlertError
`

    useEffect(() => {
        const fetchProducts = () => {
            setIsLoading(true);
            fetchBurgerIngredients()
                .then(response => {
                    setIngredients(response.data);
                    setIsLoading(false);
                })
                .catch(error => {
                    setIsLoading(false);
                    if (error.response) {
                        const errorStatus = getErrorStatus(error as AxiosError);

                        if (errorStatus === 404) {
                            AlertError(
                                "Запрашиваемой страницы не существует!",
                                error.message
                            );
                        }
                    } else if (error.request) {
                        AlertError(
                            "Не правильные параметры запроса!",
                            error.message
                        );
                    } else {
                        AlertError(
                            "Не удалось получить список ингредиентов для конструктора!",
                            error.message
                        );
                    }
                });
        };
        void fetchProducts();
    }, []);

`

2021-12-08 09:51 UTC, EvgeniyBudaev commented on src/api/menu.ts
> +const baseUrl = "https://norma.nomoreparties.space/api/ingredients";
Исправил

2021-12-08 09:51 UTC, EvgeniyBudaev commented on src/components/burger-constructor/burger-constructor.tsx
> +                    ingredients.map(product => (
Исправил

2021-12-08 09:51 UTC, EvgeniyBudaev commented on src/components/ingredient-details/ingredient-details.module.css
> +}
Исправил

2021-12-08 09:51 UTC, EvgeniyBudaev commented on src/components/order/order.tsx
> +    const BUN = "bun";
Исправил

2021-12-08 09:52 UTC, EvgeniyBudaev commented on src/components/order/order.tsx
> +    }, [ingredients]);
Исправил

2021-12-08 10:52 UTC, grishbar commented on src/components/order/order.tsx
> +                setIsLoading(false);
Привет, ты не совсем правильно меня понял, измени у себя юрл на невалидный, и попробуй в catch что нибудь вывести, ты увидишь, что у тебя ничего не выводится, так как до этого блока даже не доходит (отрабатывает catch в твоей функции fetchBurgerIngredients). Ты используешь axios и он отлавливает ошибки и отправлят их в блок catch, но если бы axios не было при выполненном запросе, но не 2xx статусе, ты бы попадал в блок then, в котором нужно проверить, что статус ответа валидный, так , что тут у тебя код рабочий, правда сейас второй catch излишний, так , что можешь выкинуть ошибку в catch в menu.ts , тогда вот этот catch будет отрабатывать. Но я изначально хотел, чтобы ты проверял [response.ok ](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) и если false то выкиидывал ошибку, да c axios это будет излишним, так, что к исправлению не обязательно

2021-12-08 10:54 UTC, grishbar commented
Круто, все моменты исправил, работа стала намного лучше, можешь еще подумать над тем, как делаешь запрос, попробовать замокать даннные и по присылать ответы на запрос с разными ошибками и посмотреть, что происходит например при помощи [fiddler](https://docs.telerik.com/fiddler-everywhere/introduction?_ga=2.107725698.1861010946.1638960837-196296126.1638960837)

2021-12-09 03:37 UTC, merged